sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: PHP_VERSION=7.3 WP_VERSION=latest
    - php: 7.2
      env: PHP_VERSION=7.2 WP_VERSION=latest
    - php: 7.2
      env: PHP_VERSION=7.2 WP_TRAVISCI=phpcs
    - php: 7.1
      env: PHP_VERSION=7.1 WP_VERSION=latest
    - php: 7.0
      env: PHP_VERSION=7.0 WP_VERSION=latest
    - php: 7.0
      env: PHP_VERSION=7.0 WP_VERSION=trunk
    - php: 5.6
      env: PHP_VERSION=5.6 WP_VERSION=5.0
    - php: 5.6
      env: PHP_VERSION=5.6 WP_VERSION=4.9
    allow_failures:
    - env: PHP_VERSION=5.6 WP_VERSION=5.0
    - env: PHP_VERSION=5.6 WP_VERSION=4.9


install:
  - |
    cd $TRAVIS_BUILD_DIR
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
       cp .env.dist .env
      composer install-wp-tests
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source --no-interaction
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require \
        squizlabs/php_codesniffer \
        phpcompatibility/phpcompatibility-wp wp-coding-standards/wpcs \
        dealerdirect/phpcodesniffer-composer-installer
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-dev
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      vendor/bin/codecept run wpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      vendor/bin/phpcs \
        ql-search.php \
        class-inflect.php \
        access-functions.php \
        includes/*.php --standard=WordPress
    fi
